const permissions = [
  "CAN_VIEW_TRANSACTIONS",
  "CAN_CREATE_TRANSACTIONS",
  "CAN_UPDATE_TRANSACTIONS",
  "CAN_VIEW_USERS",
  "CAN_CREATE_USERS",
  "CAN_UPDATE_USERS",
  "CAN_VIEW_UPLOADS",
  "CAN_CREATE_SETTLEMENT_UPLOADS",
  "CAN_CREATE_CHARGEBACK_UPLOADS",
  "CAN_VIEW_SETTLEMENTS",
  "CAN_CREATE_SETTLEMENTS",
  "CAN_UPDATE_SETTLEMENTS",
  "CAN_VIEW_CHARGEBACKS",
  "CAN_CREATE_CHARGEBACKS",
  "CAN_UPDATE_CHARGEBACKS",
  "CAN_VIEW_ROLES",
  "CAN_CREATE_ROLES",
  "CAN ASSIGN_ROLE_PERMISSIONS",
  "CAN_REVOKE_ROLE_PERMISSIONS",
];


